### ISSUE TITLE
Site detected but not added to the list...

### ISSUE THREAD

**Issue by rodrigograca31** [jkingsman/get-git#7]
Hi,

The extension detected a website but it did not showed the number "1" on the extension icon... 

I went to check and it wasn't on the "Vulnerable Sites" table...
(I rechecked again... and nothing)

Thanks.

**Comment by jkingsman** [comment]
Interesting... In general, I'm recommending all Get Git users migrate to [Bishop](https://github.com/jkingsman/Bishop), the successor to GG which can do everything GG can and more (add the demo rules and just enable the Git rules, setting the whitelist as appropriate). That being said, I don't want to just dismiss this issue, as a good amount of the codebase is the same.

Can you provide me the URL of the site that behaves this way, please? Does the problem present when you use Bishop as well?

**Comment by rodrigograca31** [comment]
@jkingsman Yheaa I noticed you doing that... I don't like bishop because we need to specify the URL... 
I lie Get Git because it scans all sites that i visit...

I did not provided the URL because obvious reasons... I will send it to you via e-mail...
It doesn't happen on Bishop...

**Comment by jkingsman** [comment]
I got your email, and I'll check on that later this week (sorry for the slo mo dev work; I'm in university and studies come first).

You mentioned also that you don't like to use Bishop because of the explicit whitelisting. The whitelist is just a regex, so if you're sure that you won't be running afoul of any websites and are okay with a scanning everyone like Get Git does, you can leave the whitelist box blank and it will scan all websites. Hopefully, if the problem isn't present in Bishop, that might allow you to make the move from Get Git.

**Comment by rodrigograca31** [comment]
(We all have priorities) :)

Yheaa, if we leave it empty it works on all!!! (Now I have to disable all the rules except the git rules....)
(This should be written there...)

**Comment by jkingsman** [comment]
Good call. Just added a note about that regex; should hit the store in an hour or so. (Also, note the `Disable All` button haha :smile:)
